// playground/vue/App.vue
<script setup lang="ts">
// Vue playground for @fft-visualizer/vue. The control panel is rendered straight
// from the shared descriptors, so this file only has to bind state — the set of
// controls, their ranges and their visibility rules live in playground/shared
// and stay identical across the core, Vue, React and Nuxt apps.
//
// The Nuxt playground renders this same component rather than a copy of it: Nuxt
// changes nothing about how the wrapper is used, only where it may render, so a
// second 250-line SFC would exist purely to drift out of parity with this one.
// The heading is a prop and the strapline a slot so it can still label itself.
import { computed, reactive, ref, onMounted, onUnmounted } from 'vue'
import { FFTVisualizer } from '@fft-visualizer/vue'
import {
  builtinPresets,
  initialSettings,
  type FftPreset,
  type FftPresetSettings
} from '@fft-visualizer/playground-shared/presets'
import {
  visibleSections,
  formatValue,
  type Control
} from '@fft-visualizer/playground-shared/controls'
import { createRadioAudio, SOMA } from '@fft-visualizer/playground-shared/radioAudio'
import {
  playgrounds,
  DOCS_URL,
  REPO_URL,
  type PlaygroundId
} from '@fft-visualizer/playground-shared/playgrounds'

// `active` is what the Nuxt playground overrides: it renders this same component,
// so the switcher has to be able to highlight a different entry than Vue's.
withDefaults(defineProps<{ title?: string, active?: PlaygroundId }>(), {
  title: '@fft-visualizer/vue Playground',
  active: 'vue'
})

// The visual settings the controls edit. Data-source settings live in the header
// selector below, not here — they aren't part of a preset.
const settings = reactive<FftPresetSettings>({ ...initialSettings })

// Sections come pre-filtered: controls whose `visible` predicate is false drop
// out, and a section left with nothing to show disappears entirely.
const sections = computed(() => visibleSections(settings))

function setOption<K extends keyof FftPresetSettings>(key: K, value: FftPresetSettings[K]) {
  settings[key] = value
}

// The three input handlers carry the casts the descriptors can't express: a
// Control's `key` is the whole union of setting names, so TypeScript can't know
// that a checkbox only ever addresses a boolean one.
function onCheckbox(control: Control, event: Event) {
  const { checked } = event.target as HTMLInputElement
  setOption(control.key, checked as FftPresetSettings[typeof control.key])
}

function onRange(control: Control, event: Event) {
  const { value } = event.target as HTMLInputElement
  setOption(control.key, Number(value) as FftPresetSettings[typeof control.key])
}

function onSelect(control: Extract<Control, { kind: 'select' }>, event: Event) {
  const { value } = event.target as HTMLSelectElement
  setOption(control.key, (control.numeric ? Number(value) : value) as FftPresetSettings[typeof control.key])
}

function rotate() {
  setOption('rotation', ((settings.rotation + 90) % 360) as FftPresetSettings['rotation'])
}

// ---- Presets ----
// Built-ins ship with the playground; user presets persist in localStorage.
const USER_PRESETS_KEY = 'fft-playground-user-presets'
const userPresets = ref<FftPreset[]>([])
const selectedPreset = ref('')
const presetName = ref('')

const isUserPreset = computed(() => userPresets.value.some(p => p.name === selectedPreset.value))

function persistUserPresets() {
  localStorage.setItem(USER_PRESETS_KEY, JSON.stringify(userPresets.value))
}

function applyPreset(name: string) {
  const preset = userPresets.value.find(p => p.name === name) ?? builtinPresets.find(p => p.name === name)
  if (!preset) return
  Object.assign(settings, preset.settings)
  // Saving again with the name prefilled overwrites a user preset in place.
  presetName.value = isUserPreset.value ? name : ''
}

function savePreset() {
  const name = presetName.value.trim()
  if (!name) return
  const preset: FftPreset = { name, settings: { ...settings } }
  const existing = userPresets.value.findIndex(p => p.name === name)
  if (existing >= 0) userPresets.value[existing] = preset
  else userPresets.value.push(preset)
  persistUserPresets()
  selectedPreset.value = name
}

function deletePreset() {
  if (!isUserPreset.value) return
  userPresets.value = userPresets.value.filter(p => p.name !== selectedPreset.value)
  persistUserPresets()
  selectedPreset.value = ''
  presetName.value = ''
}

onMounted(() => {
  try {
    const raw = localStorage.getItem(USER_PRESETS_KEY)
    if (raw) userPresets.value = JSON.parse(raw) as FftPreset[]
  } catch { /* corrupt storage — start fresh */ }
})

// ---- Data source ----
// Empty ws URL by default so the hosted (HTTPS) demo never auto-connects to an
// insecure ws:// endpoint. Enter your own wss:// server.
//
// 'radio' is the playground's own name for the visualizer's `external` mode: the
// shared radio engine analyses a live stream and feeds frames in through the
// component's feedData, exactly as a consumer would with their own source.
const source = ref<'radio' | 'local' | 'websocket'>('radio')
const websocketUrl = ref('')
const audioSource = ref<'mic' | 'display'>('mic')
const audioDeviceId = ref('')

const vizMode = computed(() => (source.value === 'radio' ? 'external' : source.value))

const fftRef = ref<InstanceType<typeof FFTVisualizer>>()

const radio = createRadioAudio()
const radioPlaying = ref(false)

// In radio mode the visualizer is 'connected' from the moment the source is
// picked — `external` renders whatever it was last fed — so the button has to
// track the stream rather than isConnected.
const isActive = computed(() =>
  source.value === 'radio' ? radioPlaying.value : (fftRef.value?.isConnected ?? false))

function stopRadio() {
  if (!radioPlaying.value) return
  radio.stop()
  radioPlaying.value = false
}

function startRadio() {
  radioPlaying.value = true
  // Feed left/right only while Stereo is on: the core mirrors mono data across
  // both channels itself, but never derives the mono buffer from a stereo pair,
  // so the non-stereo layout would have nothing to draw.
  radio.start((mono, left, right) => {
    if (settings.stereo) fftRef.value?.feedData(mono, left, right)
    else fftRef.value?.feedData(mono)
  }).catch(() => {
    // Blocked stream or a dead proxy — drop back to a stopped button.
    radioPlaying.value = false
  })
}

function toggleConnection() {
  // The radio branch stays inside the click handler: autoplay policy only allows
  // playback to begin from a user gesture.
  if (source.value === 'radio') {
    if (radioPlaying.value) stopRadio()
    else startRadio()
  } else if (fftRef.value?.isConnected) {
    fftRef.value.disconnect()
  } else {
    fftRef.value?.connect()
  }
}

// Switching away has to stop the stream — nothing else would, and it would keep
// playing over whatever source comes next.
function onSourceChange() {
  stopRadio()
}

// Switching device mid-capture needs a reconnect to take effect.
function onDeviceChange() {
  if (fftRef.value?.isConnected && source.value === 'local') {
    fftRef.value.disconnect()
    fftRef.value.connect()
  }
}

// ---- Fullscreen ----
const vizContainer = ref<HTMLElement>()
const fullscreenEl = ref<Element | null>(null)

function toggleFullscreen() {
  const el = vizContainer.value
  if (!el) return
  if (document.fullscreenElement === el) document.exitFullscreen()
  else el.requestFullscreen()
}

function onFullscreenChange() {
  fullscreenEl.value = document.fullscreenElement
}

onMounted(() => document.addEventListener('fullscreenchange', onFullscreenChange))
onUnmounted(() => {
  document.removeEventListener('fullscreenchange', onFullscreenChange)
  stopRadio()
})
</script>

<template>
  <nav class="playground-nav">
    <div class="playground-nav-inner">
      <a class="playground-nav-brand" :href="DOCS_URL">FFT Visualizer</a>
      <div class="playground-nav-links">
        <a
          v-for="p in playgrounds"
          :key="p.id"
          :href="p.href"
          :class="{ active: p.id === active }"
          :aria-current="p.id === active ? 'page' : undefined"
        >{{ p.label }}</a>
      </div>
      <a class="playground-nav-repo" :href="REPO_URL">GitHub</a>
    </div>
  </nav>

  <div class="playground">
    <header>
      <div>
        <h1>{{ title }}</h1>
        <div class="subtitle">
          <slot name="subtitle">
            The <code>&lt;FFTVisualizer&gt;</code> component, driven by reactive props.
          </slot>
        </div>
      </div>
      <div class="source-selector">
        <label for="mode">Mode</label>
        <select id="mode" v-model="source" @change="onSourceChange">
          <option value="radio">Radio (SomaFM)</option>
          <option value="local">Microphone (WASM)</option>
          <option value="websocket">WebSocket</option>
        </select>
        <template v-if="source === 'local'">
          <select v-model="audioSource" @change="onDeviceChange">
            <option value="mic">Microphone</option>
            <option value="display">System Audio</option>
          </select>
          <select
            v-if="audioSource === 'mic' && (fftRef?.audioDevices?.length ?? 0) > 1"
            v-model="audioDeviceId"
            @change="onDeviceChange"
          >
            <option value="">Default</option>
            <option
              v-for="device in fftRef?.audioDevices ?? []"
              :key="device.deviceId"
              :value="device.deviceId"
            >{{ device.label || device.deviceId }}</option>
          </select>
        </template>
        <input
          v-if="source === 'websocket'"
          v-model="websocketUrl"
          class="text-input"
          type="text"
          placeholder="wss://your-server:port"
        />
        <span v-if="source === 'radio'" class="radio-info">
          <a :href="SOMA.station" target="_blank" rel="noopener">{{ SOMA.name }}</a>
          on SomaFM — <a :href="SOMA.support" target="_blank" rel="noopener">support them</a>
        </span>
        <button
          class="connect-btn"
          :class="{ disconnect: isActive }"
          @click="toggleConnection"
        >{{ isActive ? 'Disconnect' : 'Connect' }}</button>
      </div>
    </header>

    <div ref="vizContainer" class="visualizer-container">
      <FFTVisualizer
        ref="fftRef"
        v-bind="settings"
        :mode="vizMode"
        :websocket-url="websocketUrl || undefined"
        :audio-source="audioSource"
        :audio-device-id="audioDeviceId || undefined"
      />
    </div>
    <button class="fullscreen-btn" @click="toggleFullscreen">
      {{ fullscreenEl === vizContainer ? '⛶ Exit Fullscreen' : '⛶ Fullscreen' }}
    </button>

    <div class="presets-row">
      <label for="preset">Preset</label>
      <select id="preset" v-model="selectedPreset" @change="applyPreset(selectedPreset)">
        <option value="" disabled>Choose a preset…</option>
        <optgroup label="Built-in">
          <option v-for="p in builtinPresets" :key="p.name" :value="p.name">{{ p.name }}</option>
        </optgroup>
        <optgroup v-if="userPresets.length" label="Saved">
          <option v-for="p in userPresets" :key="p.name" :value="p.name">{{ p.name }}</option>
        </optgroup>
      </select>
      <input v-model="presetName" class="text-input preset-name" type="text" placeholder="Save as…" />
      <button @click="savePreset">Save</button>
      <button v-if="isUserPreset" @click="deletePreset">Delete</button>
    </div>

    <div class="control-sections">
      <section v-for="section in sections" :key="section.id" class="control-section">
        <div class="control-section-title">{{ section.label }}</div>
        <div
          v-for="control in section.controls"
          :key="control.key"
          class="control-group"
          :class="control.kind"
        >
          <button v-if="control.kind === 'rotate'" @click="rotate">
            {{ control.label }} ({{ settings.rotation }}°)
          </button>
          <label v-else-if="control.kind === 'checkbox'">
            <input
              type="checkbox"
              :checked="settings[control.key] as boolean"
              @change="onCheckbox(control, $event)"
            />
            {{ control.label }}
          </label>
          <label v-else-if="control.kind === 'select'">
            <span>{{ control.label }}</span>
            <select :value="String(settings[control.key])" @change="onSelect(control, $event)">
              <option v-for="o in control.options" :key="o.value" :value="o.value">{{ o.label }}</option>
            </select>
          </label>
          <label v-else>
            <span>{{ control.label }}: {{ formatValue(control, settings) }}</span>
            <input
              type="range"
              :min="control.min"
              :max="control.max"
              :step="control.step"
              :value="settings[control.key] as number"
              @input="onRange(control, $event)"
            />
          </label>
        </div>
      </section>
    </div>
  </div>
</template>

// playground/react/App.tsx
// React playground for @fft-visualizer/react. The control panel is rendered
// straight from the shared descriptors, so this file only has to bind state —
// the set of controls, their ranges and their visibility rules live in
// playground/shared and stay identical across the core, Vue, React and Nuxt apps.
import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { FFTVisualizer, type AudioDevice, type FFTVisualizerHandle } from '@fft-visualizer/react'
import {
  builtinPresets,
  initialSettings,
  type FftPreset,
  type FftPresetSettings
} from '@fft-visualizer/playground-shared/presets'
import {
  visibleSections,
  formatValue,
  type Control
} from '@fft-visualizer/playground-shared/controls'
import { createRadioAudio, SOMA, type RadioAudio } from '@fft-visualizer/playground-shared/radioAudio'
import { playgrounds, DOCS_URL, REPO_URL } from '@fft-visualizer/playground-shared/playgrounds'

const USER_PRESETS_KEY = 'fft-playground-user-presets'

function loadUserPresets(): FftPreset[] {
  try {
    const raw = localStorage.getItem(USER_PRESETS_KEY)
    return raw ? (JSON.parse(raw) as FftPreset[]) : []
  } catch {
    return [] // corrupt storage — start fresh
  }
}

export default function App() {
  // The visual settings the controls edit. Data-source settings live in the
  // header selector below, not here — they aren't part of a preset.
  const [settings, setSettings] = useState<FftPresetSettings>(initialSettings)

  // Sections come pre-filtered: controls whose `visible` predicate is false drop
  // out, and a section left with nothing to show disappears entirely.
  const sections = useMemo(() => visibleSections(settings), [settings])

  function setOption<K extends keyof FftPresetSettings>(key: K, value: FftPresetSettings[K]) {
    setSettings(prev => ({ ...prev, [key]: value }) as FftPresetSettings)
  }

  // ---- Presets ----
  // Built-ins ship with the playground; user presets persist in localStorage.
  const [userPresets, setUserPresets] = useState<FftPreset[]>(loadUserPresets)
  const [selectedPreset, setSelectedPreset] = useState('')
  const [presetName, setPresetName] = useState('')

  const isUserPreset = userPresets.some(p => p.name === selectedPreset)

  function persistUserPresets(presets: FftPreset[]) {
    setUserPresets(presets)
    localStorage.setItem(USER_PRESETS_KEY, JSON.stringify(presets))
  }

  function applyPreset(name: string) {
    setSelectedPreset(name)
    const preset = userPresets.find(p => p.name === name) ?? builtinPresets.find(p => p.name === name)
    if (!preset) return
    setSettings(preset.settings)
    // Saving again with the name prefilled overwrites a user preset in place.
    setPresetName(userPresets.some(p => p.name === name) ? name : '')
  }

  function savePreset() {
    const name = presetName.trim()
    if (!name) return
    const preset: FftPreset = { name, settings: { ...settings } }
    const existing = userPresets.findIndex(p => p.name === name)
    persistUserPresets(existing >= 0
      ? userPresets.map((p, i) => (i === existing ? preset : p))
      : [...userPresets, preset])
    setSelectedPreset(name)
  }

  function deletePreset() {
    if (!isUserPreset) return
    persistUserPresets(userPresets.filter(p => p.name !== selectedPreset))
    setSelectedPreset('')
    setPresetName('')
  }

  // ---- Data source ----
  // Empty ws URL by default so the hosted (HTTPS) demo never auto-connects to an
  // insecure ws:// endpoint. Enter your own wss:// server.
  //
  // 'radio' is the playground's own name for the visualizer's `external` mode: the
  // shared radio engine analyses a live stream and feeds frames in through the
  // component's feedData, exactly as a consumer would with their own source.
  const [source, setSource] = useState<'radio' | 'local' | 'websocket'>('radio')
  const [websocketUrl, setWebsocketUrl] = useState('')
  const [audioSource, setAudioSource] = useState<'mic' | 'display'>('mic')
  const [audioDeviceId, setAudioDeviceId] = useState('')

  const vizMode = source === 'radio' ? 'external' : source

  const fftRef = useRef<FFTVisualizerHandle>(null)

  // The handle exposes isConnected as a plain getter, so unlike the Vue wrapper's
  // reactive ref it can't drive a re-render — mirror it into state via the events.
  const [isConnected, setIsConnected] = useState(false)

  // Same story for the device list: the wrapper doesn't surface the core's
  // `audiostate` event, so pull the devices once capture has started (which is
  // also when the mic permission that populates their labels has been granted).
  const [audioDevices, setAudioDevices] = useState<AudioDevice[]>([])
  useEffect(() => {
    if (!isConnected || source !== 'local') return
    void fftRef.current?.getAudioDevices().then(setAudioDevices).catch(() => { /* permission denied */ })
  }, [isConnected, source])

  // ---- Radio ----
  // Lazy ref rather than state: the engine is a stable object for the lifetime of
  // the app, and re-creating it per render would leak an AudioContext per click.
  const radioRef = useRef<RadioAudio | null>(null)
  radioRef.current ??= createRadioAudio()
  const [radioPlaying, setRadioPlaying] = useState(false)

  // The frame callback outlives the render that installed it, so it has to read
  // `stereo` from a ref — a captured value would freeze at whatever it was when
  // playback started and stop matching the layout on screen.
  const stereoRef = useRef(settings.stereo)
  useEffect(() => { stereoRef.current = settings.stereo }, [settings.stereo])

  // In radio mode the visualizer is 'connected' from the moment the source is
  // picked — `external` renders whatever it was last fed — so the button has to
  // track the stream rather than isConnected.
  const isActive = source === 'radio' ? radioPlaying : isConnected

  function stopRadio() {
    radioRef.current?.stop()
    setRadioPlaying(false)
  }

  function startRadio() {
    setRadioPlaying(true)
    // Feed left/right only while Stereo is on: the core mirrors mono data across
    // both channels itself, but never derives the mono buffer from a stereo pair,
    // so the non-stereo layout would have nothing to draw.
    radioRef.current?.start((mono, left, right) => {
      if (stereoRef.current) fftRef.current?.feedData(mono, left, right)
      else fftRef.current?.feedData(mono)
    }).catch(() => {
      // Blocked stream or a dead proxy — drop back to a stopped button.
      setRadioPlaying(false)
    })
  }

  // Leaving the page has to stop the stream; nothing else would.
  useEffect(() => () => radioRef.current?.stop(), [])

  function toggleConnection() {
    // The radio branch stays inside the click handler: autoplay policy only allows
    // playback to begin from a user gesture.
    if (source === 'radio') {
      if (radioPlaying) stopRadio()
      else startRadio()
    } else if (isConnected) {
      fftRef.current?.disconnect()
    } else {
      fftRef.current?.connect()
    }
  }

  // Switching source or device mid-capture needs a reconnect to take effect.
  // Done as an effect keyed on the two options rather than inside the change
  // handlers, because a setState hasn't reached the core yet at that point —
  // React flushes the wrapper's own option-forwarding effect first (child before
  // parent), so by the time this runs the core already has the new value.
  useEffect(() => {
    if (!isConnected || source !== 'local') return
    fftRef.current?.disconnect()
    fftRef.current?.connect()
    // isConnected/source are deliberately read but not tracked: a reconnect should
    // follow a source change only, not the connect that one itself triggers.
  }, [audioSource, audioDeviceId])

  // ---- Fullscreen ----
  const containerRef = useRef<HTMLDivElement>(null)
  const [isFullscreen, setIsFullscreen] = useState(false)

  useEffect(() => {
    const onChange = () => setIsFullscreen(document.fullscreenElement === containerRef.current)
    document.addEventListener('fullscreenchange', onChange)
    return () => document.removeEventListener('fullscreenchange', onChange)
  }, [])

  function toggleFullscreen() {
    const el = containerRef.current
    if (!el) return
    if (document.fullscreenElement === el) void document.exitFullscreen()
    else void el.requestFullscreen()
  }

  // The casts here are the ones the descriptors can't express: a Control's `key`
  // is the whole union of setting names, so TypeScript can't know that a checkbox
  // only ever addresses a boolean one.
  function renderControl(control: Control): ReactNode {
    if (control.kind === 'rotate') {
      return (
        <button onClick={() => setOption('rotation', ((settings.rotation + 90) % 360) as FftPresetSettings['rotation'])}>
          {control.label} ({settings.rotation}°)
        </button>
      )
    }
    if (control.kind === 'checkbox') {
      return (
        <label>
          <input
            type="checkbox"
            checked={settings[control.key] as boolean}
            onChange={e => setOption(control.key, e.target.checked as FftPresetSettings[typeof control.key])}
          />
          {control.label}
        </label>
      )
    }
    if (control.kind === 'select') {
      return (
        <label>
          <span>{control.label}</span>
          <select
            value={String(settings[control.key])}
            onChange={e => setOption(
              control.key,
              (control.numeric ? Number(e.target.value) : e.target.value) as FftPresetSettings[typeof control.key]
            )}
          >
            {control.options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
          </select>
        </label>
      )
    }
    return (
      <label>
        <span>{control.label}: {formatValue(control, settings)}</span>
        <input
          type="range"
          min={control.min}
          max={control.max}
          step={control.step}
          value={settings[control.key] as number}
          onChange={e => setOption(control.key, Number(e.target.value) as FftPresetSettings[typeof control.key])}
        />
      </label>
    )
  }

  return (
    <>
      <nav className="playground-nav">
        <div className="playground-nav-inner">
          <a className="playground-nav-brand" href={DOCS_URL}>FFT Visualizer</a>
          <div className="playground-nav-links">
            {playgrounds.map(p => (
              <a
                key={p.id}
                href={p.href}
                className={p.id === 'react' ? 'active' : undefined}
                aria-current={p.id === 'react' ? 'page' : undefined}
              >
                {p.label}
              </a>
            ))}
          </div>
          <a className="playground-nav-repo" href={REPO_URL}>GitHub</a>
        </div>
      </nav>

      <div className="playground">
        <header>
          <div>
            <h1>@fft-visualizer/react Playground</h1>
            <div className="subtitle">
              The <code>&lt;FFTVisualizer&gt;</code> component, driven by React state.
            </div>
          </div>
          <div className="source-selector">
            <label htmlFor="mode">Mode</label>
            <select
              id="mode"
              value={source}
              onChange={e => {
                // Switching away has to stop the stream, or it keeps playing over
                // whatever source comes next.
                stopRadio()
                setSource(e.target.value as 'websocket' | 'local' | 'radio')
              }}
            >
              <option value="radio">Radio (SomaFM)</option>
              <option value="local">Microphone (WASM)</option>
              <option value="websocket">WebSocket</option>
            </select>
            {source === 'local' && (
              <>
                <select
                  value={audioSource}
                  onChange={e => setAudioSource(e.target.value as 'mic' | 'display')}
                >
                  <option value="mic">Microphone</option>
                  <option value="display">System Audio</option>
                </select>
                {audioSource === 'mic' && audioDevices.length > 1 && (
                  <select
                    value={audioDeviceId}
                    onChange={e => setAudioDeviceId(e.target.value)}
                  >
                    <option value="">Default</option>
                    {audioDevices.map(device => (
                      <option key={device.deviceId} value={device.deviceId}>
                        {device.label || device.deviceId}
                      </option>
                    ))}
                  </select>
                )}
              </>
            )}
            {source === 'websocket' && (
              <input
                className="text-input"
                type="text"
                placeholder="wss://your-server:port"
                value={websocketUrl}
                onChange={e => setWebsocketUrl(e.target.value)}
              />
            )}
            {source === 'radio' && (
              <span className="radio-info">
                <a href={SOMA.station} target="_blank" rel="noopener">{SOMA.name}</a>
                {' '}on SomaFM — <a href={SOMA.support} target="_blank" rel="noopener">support them</a>
              </span>
            )}
            <button
              className={isActive ? 'connect-btn disconnect' : 'connect-btn'}
              onClick={toggleConnection}
            >{isActive ? 'Disconnect' : 'Connect'}</button>
          </div>
        </header>

        <div ref={containerRef} className="visualizer-container">
          <FFTVisualizer
            ref={fftRef}
            {...settings}
            mode={vizMode}
            websocketUrl={websocketUrl || undefined}
            audioSource={audioSource}
            audioDeviceId={audioDeviceId || undefined}
            onConnected={() => setIsConnected(true)}
            onDisconnected={() => setIsConnected(false)}
          />
        </div>
        <button className="fullscreen-btn" onClick={toggleFullscreen}>
          {isFullscreen ? '⛶ Exit Fullscreen' : '⛶ Fullscreen'}
        </button>

        <div className="presets-row">
          <label htmlFor="preset">Preset</label>
          <select id="preset" value={selectedPreset} onChange={e => applyPreset(e.target.value)}>
            <option value="" disabled>Choose a preset…</option>
            <optgroup label="Built-in">
              {builtinPresets.map(p => <option key={p.name} value={p.name}>{p.name}</option>)}
            </optgroup>
            {userPresets.length > 0 && (
              <optgroup label="Saved">
                {userPresets.map(p => <option key={p.name} value={p.name}>{p.name}</option>)}
              </optgroup>
            )}
          </select>
          <input
            className="text-input preset-name"
            type="text"
            placeholder="Save as…"
            value={presetName}
            onChange={e => setPresetName(e.target.value)}
          />
          <button onClick={savePreset}>Save</button>
          {isUserPreset && <button onClick={deletePreset}>Delete</button>}
        </div>

        <div className="control-sections">
          {sections.map(section => (
            <section key={section.id} className="control-section">
              <div className="control-section-title">{section.label}</div>
              {section.controls.map(control => (
                <div key={control.key} className={`control-group ${control.kind}`}>
                  {renderControl(control)}
                </div>
              ))}
            </section>
          ))}
        </div>
      </div>
    </>
  )
}
